### ISSUE TITLE
resolve sendgrid problem and git rebase problems

### ISSUE THREAD

**Issue by techieeliot** [leviking/KikiSaver#157]
### Tasks

- [x] Stash commits

- [x] Delete branches

- [ ] Contact Tai to delete PR and clear cache

- [ ] Fetch upstream on after Tai resets

- [ ] Apply stash and new PR

![image](https://user-images.githubusercontent.com/19453294/80985235-8d470580-8df4-11ea-89b5-3b51c3490a21.png)

**Comment by techieeliot** [comment]
Hey Levi, after the rebase I'm getting this where I'm co-authored on every commit. Will I need to manually fix this on each commit?

![Screen Shot 2020-05-02 at 5 22 03 PM](https://user-images.githubusercontent.com/19453294/80893599-75a73a00-8c99-11ea-945e-16d129c29c9a.png)
